### ISSUE TITLE
Types for typescript are not correctly referenced

### ISSUE THREAD

**Issue by remyguillaume** [WebReflection/uhtml#143]
Hi there,

I've just migrated to uHtml 4.7.0, and it seems that the package.json has a wrong exports for types definition (for usage with typescript).
```
"exports": {
    ".": {
      "import": "./esm/index.js",
      "types": {
        "require": "./types/index.d.cts",
        "default": "./types/index.d.mts"
      },
      "default": "./cjs/index.js"
    },
...
...
```

Actually there is no mts of cts file. I think this should be repalced with 

```
    ".": {
      "import": "./esm/index.js",
      "types": "./types/index.d.ts",
      "default": "./cjs/index.js"
    },
...
...
```

Is it ok for you if I open a PR for this?
Thanks.

**Comment by eatsjobs** [comment]
this should fix it: https://github.com/WebReflection/uhtml/pull/145

**Comment by devinivy** [comment]
Just want to help lay out what's going on here a little more explicitly.

Right now on fresh installs of uhtml v4.7.0 the types are broken, at least for ESM users.  There's a simple reason for that: the type files referenced in package.json have extension .mts while the published package contains type files with extension .ts.  Here's an example from unpkg: [package.json](https://unpkg.com/browse/uhtml@4.7.0/package.json) (see each `exports.types.default`) vs. files built in [types/](https://unpkg.com/browse/uhtml@4.7.0/types/).

Right now when I clone uhtml and run `npm run build:types` I get an error which is addressed by #145: 
```
$ npm run build:types

> uhtml@4.7.0 build:types
> rm -rf types && npx tsc -p tsconfig.json && node rollup/ts.fix.js

esm/dom/utils.js:7:14 - error TS4118: The type of this node cannot be serialized because its property '__@nodeType@27005' cannot be serialized.
```

But the types/ directory is still written.  It's just not getting to the `node rollup/ts.fix.js` step introduced from #120 and #121.  So what's happening here is that the build step is partially failing, and as a result the contents of the types/ directory doesn't match the type files referenced in package.json.

The fix from #145 should indeed fix the error in the build process causing this.  Still is a bit odd that the bad build went through rather than failing from the type error fixed by #145, not sure the cause of that.
